export const nodes = [
	{
		id: "A",
		type: "personNode",
		pred: ["F", "G"],
		succ: ["C", "D", "E"],
		rel: ["B"],
		gen: 0,
		position: { x: 0, y: 0 },
		data: { label: "A" },
	},
	{
		id: "B",
		type: "personNode",
		pred: ["H", "I"],
		succ: ["C", "D", "E"],
		rel: ["A"],
		gen: 0,
		position: { x: 0, y: 0 },
		data: { label: "B" },
	},
	{
		id: "C",
		type: "personNode",
		pred: ["A", "B"],
		succ: [],
		rel: [],
		gen: 0,
		position: { x: 0, y: 0 },
		data: { label: "C" },
	},
	{
		id: "D",
		type: "personNode",
		pred: ["A", "B"],
		succ: [],
		rel: ["1"],
		gen: 0,
		position: { x: 0, y: 0 },
		data: { label: "D" },
	},
	{
		id: "E",
		type: "personNode",
		pred: ["A", "B"],
		succ: [],
		rel: [],
		gen: 0,
		position: { x: 0, y: 0 },
		data: { label: "E" },
	},
	{
		id: "F",
		type: "personNode",
		pred: [],
		succ: ["A"],
		rel: ["G"],
		gen: 0,
		position: { x: 0, y: 0 },
		data: { label: "F" },
	},
	{
		id: "G",
		type: "personNode",
		pred: [],
		succ: ["A"],
		rel: ["F"],
		gen: 0,
		position: { x: 0, y: 0 },
		data: { label: "G" },
	},
	{
		id: "H",
		type: "personNode",
		pred: [],
		succ: ["B"],
		rel: ["I"],
		gen: 0,
		position: { x: 0, y: 0 },
		data: { label: "H" },
	},
	{
		id: "I",
		type: "personNode",
		pred: [],
		succ: ["B"],
		rel: ["H"],
		gen: 0,
		position: { x: 0, y: 0 },
		data: { label: "I" },
	},
	{
		id: "1",
		type: "personNode",
		pred: ["4", "5"],
		succ: ["2", "3"],
		rel: ["D"],
		gen: 0,
		position: { x: 0, y: 0 },
		data: { label: "1" },
	},
	{
		id: "2",
		type: "personNode",
		pred: ["D", "1"],
		succ: [],
		rel: [],
		gen: 0,
		position: { x: 0, y: 0 },
		data: { label: "2" },
	},
	{
		id: "3",
		type: "personNode",
		pred: ["D", "1"],
		succ: [],
		rel: [],
		gen: 0,
		position: { x: 0, y: 0 },
		data: { label: "3" },
	},
	{
		id: "4",
		type: "personNode",
		pred: [],
		succ: ["1"],
		rel: ["5"],
		gen: 0,
		position: { x: 0, y: 0 },
		data: { label: "4" },
	},
	{
		id: "5",
		type: "personNode",
		pred: ["6"],
		succ: ["1"],
		rel: ["4"],
		gen: 0,
		position: { x: 0, y: 0 },
		data: { label: "5" },
	},
	{
		id: "6",
		type: "personNode",
		pred: [],
		succ: ["5"],
		rel: [],
		gen: 0,
		position: { x: 0, y: 0 },
		data: { label: "6" },
	},
];
